name: ci_cd.yml
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js 20
              uses: actions/setup-node@v3  # Ensure to use the latest version of setup-node
              with:
                  node-version: '20'

            - name: Deploy to Server 1
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEPLOY_HOST }}
                  username: ${{ secrets.DEPLOY_USER }}
                  key: ${{ secrets.DEPLOY_KEY }}
                  script: |
                    if [ "${{ github.ref }}" = "refs/heads/main" ]; then
                      sh /home/ubuntu/scripts/cicd/TANCEM_pis_express_staging.sh
